spring.output.ansi.enabled: ALWAYS

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        show-sql: true
        format_sql: true

## todo
user:
  secret:
    key: "ok0"

---
datasource:
  user:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/financial_user?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
      username: root
      password: root
      pool-name: HikariPool-user-master
      maximum-pool-size: 2
    slave:
      jdbc-url: jdbc:mysql://localhost:3306/financial_user?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
      username: root
      password: root
      pool-name: HikariPool-user-slave
      maximum-pool-size: 2